### PR TITLE
feat: add example pipelines for GCP cloud build

### PR DESCRIPTION
**Pull request by ananthkamath**

### CODE REVIEW

**Comment by TreetopTechie** [comment]
Can we remove the node installation, not sure what it is for?

**Comment by ananthkamath** [comment]
> Can we remove the node installation, not sure what it is for?

I was expecting we need node in order to run `endorctl` binary. Let me test this without node.

**Comment by ananthkamath** [comment]
> > Can we remove the node installation, not sure what it is for?
> 
> I was expecting we need node in order to run `endorctl` binary. Let me test this without node.

@TreetopTechie You are write it is not needed, tested the pipeline without nodejs and worked successfully.

**Review by TreetopTechie — APPROVED** [review]
LGTM!

**Pull request merged**
